### ISSUE TITLE
Patch 3.1 update

### ISSUE THREAD

**Issue by khamass** [jayotterbein/FFXIV-Zoom-Hack#3]
Patch 3.1 update stopped FFXIV-Zoom-Hack from working.

**Comment by jayotterbein** [comment]
Thanks for the info.  I tried looking at this morning before work, but the dx11 address seemed WAY off of what I expected, while I was trying to debug it I lost some power and will have some non-ffxiv debugging work to do today.  I'll try to get it out asap, since I use it myself, but it's possible I won't have anything until the weekend.

**Comment by jayotterbein** [comment]
Just got wind of an emergency maintenance tomorrow (time unknown): http://na.finalfantasyxiv.com/lodestone/news/detail/996bf5ef4b4f2ac8668638554d819c846522e5f3

So for now I won't fix yet, since a patch may be imminent and require another round of searching.

**Comment by jayotterbein** [comment]
The structure was modified this time around.  Finally got around to fixing it.
