### ISSUE TITLE
Dx11 broke after patch

### ISSUE THREAD

**Issue by Oopdatme** [jayotterbein/FFXIV-Zoom-Hack#5]
Last patch stopped it from working again, anyway we can get a tut on how to manually change the offsets for when this happens? Thanks

**Comment by jayotterbein** [comment]
Resolved by PR #6.  I'll get a guide up, sure. I tried to last time, for the 3.1 patch, but then the structure changed; that is a bigger deal than finding current offsets so writing the guide at the time would have been worthless because it's never happened before.

Leaving the issue open until the guide is completed.

**Comment by jayotterbein** [comment]
Finally got the guide on the readme.
