### ISSUE TITLE
Error with Net.framework (i guess)

### ISSUE THREAD

**Issue by nowa1991** [jayotterbein/FFXIV-Zoom-Hack#63]
My problem is with net framework i guess, everytime i try to open it i get an error message like ''unhandled exception in the application - source:code''

sorry for the newbie question and thx

**Comment by jayotterbein** [comment]
So far I've not heard anything like this. Do you have any screenshots, or are other applications doing this on your computer?

**Comment by nowa1991** [comment]
No, only this one. 

I can post an image, but is on spanish, i can swap the SO idiom if you have any problem

https://imgur.com/sEzu6Zb

**Comment by jayotterbein** [comment]
I can't promise this will fix the problem, but it might get us more information for what's going wrong. Try this v1.3 release https://github.com/jayotterbein/FFXIV-Zoom-Hack/releases/tag/1.3

**Comment by Turkolton** [comment]
Running into the same issue, the fix released didn't do fix it unfortunately 
i have the latest version of NETFrame could that be the issue? as i just updated my PC overall, it was working before.

Just a heads up - Love your Program and ill search for solution on my end it could be my PC not the App. dunno

**Comment by nowa1991** [comment]
Same for me, it was working before i did format.

Now that new file doesn't give me error, but asks me for update, click on update and doesn't find any update

**Comment by Turkolton** [comment]
examples:
[https://imgur.com/DK8AOei](url)
[https://imgur.com/2jIKiJL](url)

**Comment by nowa1991** [comment]
Just the exact same error

**Comment by Biggles982** [comment]
I'm getting the same error, too.

**Comment by sparkymotive** [comment]
I'm having the same issue as well.  I followed the steps on the main page to find the offset but the value doesn't update when I change zoom in the final step.  Also the offset hasn't changed(at least for DX11).

**Comment by liogame801** [comment]
I am Japanese.
I have the same problem.
The image is in Japanese, but I think it's the same error.
This issue only occurred on the initialized PC.
It was working fine before it was initialized.
Also, it is working properly on another PC.

[https://imgur.com/Z51PZDn](url)
Sorry for the Japanese error dialog

**Comment by nowa1991** [comment]
Did anyone found any solution?

**Comment by Turkolton** [comment]
> Did anyone found any solution?

i personally have not, been checking github on and off, and the issue seems to effect more people than i thought, i know people who did not post here who are now looking into paying coders a monthly 5-10$ to make them a similar application, some offered 50$ 1 time payment, and 3$ monthly to keep updating it on patches etc, (Apparently this type of code is simple for them), one of my friends reached out to people on twitter who worked on previous apps and since have stopped, i will see how it works out for my people, but if it does, i'm paying too haha.

**Comment by jayotterbein** [comment]
I didn't expect so many to have the problem, I'm wondering if it was some .NET framework update for windows

This app is MIT so any of those other coders can use everything here as-is and sell it.

**Comment by Turkolton** [comment]
> I didn't expect so many to have the problem, I'm wondering if it was some .NET framework update for windows
> 
> This app is MIT so any of those other coders can use everything here as-is and sell it.

Even if they use everything here as is and sell it to me, i will still face the same issue - as will the rest in this post, so that's not the idea,

Yeah for allot of people your app would work just fine as is and no issues which is great, but we are getting a coder to investigate the NET Frame issues and try to produce an app or code that works for the rest of us with that specific issue, and if they can't then at least tell us where the issue is specifically,

And we went with a coder through online posting that is currently working, i will share their version when/if its done and maybe it could solve the issue for others or we can incorporate it somehow on github, I'm not a fan of paying if there's a free version!

Lets see how it works out!!

**Comment by sparkymotive** [comment]
If anyone here is still having this issue, please see #62 as it worked for me.  TL;DR make a local copy of Offsets.xml

**Comment by nowa1991** [comment]
Keep getting the same error

**Comment by nowa1991** [comment]
Did anyone found a solution?

**Comment by Turkolton** [comment]
> Did anyone found a solution?

Hey Nowa, 

Assuming you downloaded the offset.xml file, head to your zoom app and place your file link in the box, make sure it ends with "Offsets.xml",  mine for example is "C:\Users\User\Downloads\Offsets.xml"

and it should work, (some ppl forget to put the .xml at the end, because the file only appears as Offsets in the destination.

**Comment by nowa1991** [comment]
Worked, thank you very much
