### ISSUE TITLE
[Enhancement] Make Dalamud Plugin Zoom-Hack

### ISSUE THREAD

**Issue by ghost** [jayotterbein/FFXIV-Zoom-Hack#65]
Could u make a plugin for dalamud? One note here is, this kind of "hack" is considered as cheating in the dalamud community, so it must be a non official plugin.

https://github.com/goatcorp/Dalamud
https://github.com/goatcorp/FFXIVQuickLauncher

**Comment by jayotterbein** [comment]
I don't have a current account with ffxiv, and I've never used the launcher or plugin framework. I'm open to accept PRs but I wouldn't be able to test anything.

The zoom code is fairly simple, and open, so anyone can also just use this code and make a different repository which is the plugin

**Comment by someONEgood** [comment]
First off I **really** appreciate this tool. Thank you for creating it.

Just wanted to add to this discussion that since Summer 2020, FFXIV has **a free trial with zero time limit** that allows you to play up to Level 60 and through Heavensward. This would allow for subscription-free testing on your end.

Just tossing it in as a possible option if you were willing.

**Comment by ghost** [comment]
Ok i found something similar as Dalamud plugin, for anyone interested:

https://github.com/daemitus/CameraPlugin
